services:
  postgres:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_DB=sample_crud
      - POSTGRES_USER=sample_crud
      - POSTGRES_PASSWORD=sample_crud
    ports:
      - 5432:5432